<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Erika Carlson">
<meta name="dcterms.date" content="2024-03-06">

<title>data-analysis-replication</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="data-analysis-replication_files/libs/clipboard/clipboard.min.js"></script>
<script src="data-analysis-replication_files/libs/quarto-html/quarto.js"></script>
<script src="data-analysis-replication_files/libs/quarto-html/popper.min.js"></script>
<script src="data-analysis-replication_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="data-analysis-replication_files/libs/quarto-html/anchor.min.js"></script>
<link href="data-analysis-replication_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="data-analysis-replication_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="data-analysis-replication_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="data-analysis-replication_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="data-analysis-replication_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="data-analysis-replication_files/libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="data-analysis-replication_files/libs/tabwid-1.1.3/tabwid.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">data-analysis-replication</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Erika Carlson </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 6, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="data-analysis-replication" class="level1 unnumbered">
<h1 class="unnumbered">Data Analysis Replication</h1>
<section id="introduction" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="introduction">Introduction</h2>
<p>Microglia are central nervous system (CNS)-resident immune cells with key roles in many neurological diseases. Microglia morphology changes in response to stimuli and is often used as a proxy for neuroinflammation and/or pathology. Mice were subjected to control or PLX (microglia depletion and repopulation) treatment, then challenged with LPS (component of bacterial membrane) to elicit a strong immune response. Brains were collected and processed for microglia imaging. This paper tested for comparability across five common ImageJ (NIH) methods used to assess microglia morphology in mice. Analyses were conducted on identical photomicrographs, as well as individual microglia cells within the photomicrographs for direct comparison. The results of the five methods indicated a lack of comparability, leading the authors to conclude that studies should combine multiple methods to achieve an accurate representation of microglia morphology.</p>
<p>This paper conducted five ImageJ-based analysis techniques, two on full 40x photomicrographs and three on single microglia cells isolated from those photomicrographs. These photomicrographs were stained for Ionized calcium binding adapter molecule 1 (Iba1). Iba1 is a cannonical microglial marker used to examine microglial reactivity. The techniques were applied to identify alterations in microglial morphology or percent coverage between <strong>Treatment</strong> groups (Control vs PLX) that had pharmacologically manipulated microglia following an inflammatory stimuli. The five analysis techniques were:</p>
<ol type="1">
<li>Percent coverage of Iba1 staining to show how much Iba1 positive staining is present in a given photomicrograph.</li>
<li>Full photomicrograph skeletal analysis to calculate an averaged number of branches, branch endpoints, and branch length among cells in the field of view.</li>
<li>Fractal analysis to quantify the spatial complexity of the individually isolated microglia.</li>
<li>Single cell skeletal analysis to quantify microglial ramification and cell body size.</li>
<li>Sholl analysis to determine the extent of branching of individual microglia via intercepts on concentric circles around the cell body.</li>
</ol>
<p>Authors then investigated microglial differences between control and treatment groups by fitting hierarchical generalized linear mixed models using {glmmTMB} package in <strong><em>R</em></strong>. The error distribution (beta, negative-binomial, gaussian, gamma) used depended on the scale of the response variable. All models included a fixed effect for treatment. Sholl analysis included additional effects, described below. Random effects structure was used for aggregated, single cell, and Sholl analysis data sets. Inferences were based on a combination of coefficient estimates (β) and their 95% confidence intervals, differences between predicted conditional means (∆), effect sizes (d), and p-values following Tukey’s adjustments for multiple comparisons using {emmeans} package in <strong><em>R</em></strong>.</p>
<p>Here, I have replicated two versions of analysis technique 1, full photomicrograph analysis of Iba1 percent coverage, and the associated visualizations (plus descriptive statistics). I also attempted to replicate the Sholl analysis and visualization.</p>
</section>
<section id="preliminaries" class="level2">
<h2 class="anchored" data-anchor-id="preliminaries">Preliminaries</h2>
<p>Load required packages</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("rempsyc")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rempsyc) <span class="co"># publication-ready t-tests in R</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>pkgs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"tidyverse"</span>, <span class="st">"skimr"</span>, <span class="st">"broom"</span>, <span class="st">"ggprism"</span>, <span class="st">"ggpubr"</span>, <span class="st">"effectsize"</span>, <span class="st">"flextable"</span>, <span class="st">"glmmTMB"</span>, <span class="st">"emmeans"</span>, <span class="st">"lme4"</span>, <span class="st">"rstatix"</span>, <span class="st">"DescTools"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">install_if_not_installed</span>(pkgs) <span class="co"># rempsyc function for easy installation</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># data wrangling and ggplot2</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr) <span class="co"># data wrangling</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom) <span class="co"># data wrangling</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggprism) <span class="co"># data visualization</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr) <span class="co"># data visualization</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize) <span class="co"># helper package for rempsyc</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(flextable) <span class="co"># helper package for rempsyc</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmmTMB) <span class="co"># frequentist model fitting, specified in paper</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans) <span class="co"># statistics, specified in paper</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4) <span class="co"># statistics</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstatix) <span class="co"># statistics</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DescTools) <span class="co"># statistics</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Tell {knitr} where to output all of the figures associated with code chunks and where to find any images to include in the “.html” output.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">fig.path =</span> <span class="st">"images/"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Read in data files</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>perc_coverage <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Perc_Coverage.csv"</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 225 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): Treatment
dbl  (2): Coverage, Perc_Cov
time (1): Animal_ID

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(perc_coverage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  Animal_ID Treatment Coverage Perc_Cov
  &lt;time&gt;    &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;
1 01:01     Control       15.5    0.155
2 01:01     Control       18.3    0.183
3 01:01     Control       17.6    0.176
4 01:01     Control       12.9    0.129
5 01:01     Control       23.8    0.238
6 01:01     Control       17.6    0.176</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>perc_coverage_avg <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Perc_Coverage_Avg.csv"</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 25 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): Treatment
dbl  (2): Avg_percent, Perc_Cov
time (1): Animal_ID

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(perc_coverage_avg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  Animal_ID Treatment Avg_percent Perc_Cov
  &lt;time&gt;    &lt;chr&gt;           &lt;dbl&gt;    &lt;dbl&gt;
1 01:01     Control          17.5    0.175
2 01:05     Control          16.7    0.167
3 01:06     Control          12.3    0.123
4 01:07     Control          17.4    0.174
5 01:08     Control          19.7    0.197
6 01:12     PLX              14.0    0.140</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>single_cell <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/Single_Cell.csv"</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 675 Columns: 16
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (1): Treatment
dbl  (14): Cohort, Region, FractalDimension(DB), Lacunarity, Density(pixels/...
time  (1): Animal_ID

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(single_cell)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 16
  Animal_ID Cohort Treatment Region `FractalDimension(DB)` Lacunarity
  &lt;time&gt;     &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;                  &lt;dbl&gt;      &lt;dbl&gt;
1 01:01          1 Control        2                   1.53      0.485
2 01:01          1 Control        2                   1.56      0.324
3 01:01          1 Control        1                   1.42      0.734
4 01:01          1 Control        2                   1.62      0.316
5 01:01          1 Control        3                   1.48      0.450
6 01:01          1 Control        2                   1.63      0.301
# ℹ 10 more variables: `Density(pixels/area)` &lt;dbl&gt;, SpanRatio &lt;dbl&gt;,
#   Circularity &lt;dbl&gt;, NumberOfEndpoints &lt;dbl&gt;, `BranchLength(um)` &lt;dbl&gt;,
#   NumberBranches &lt;dbl&gt;, body_area &lt;dbl&gt;, cell_area_C &lt;dbl&gt;,
#   body_perimeter &lt;dbl&gt;, cell_perim_C &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sholl_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/sholl_data.csv"</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 599 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (1): Treatment
dbl  (4): Cohort, Distance(um), avg_intersection_n, intern_C
time (1): Animal_ID

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sholl_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  Animal_ID Cohort Treatment `Distance(um)` avg_intersection_n intern_C
  &lt;time&gt;     &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt;              &lt;dbl&gt;    &lt;dbl&gt;
1 01:01          1 Control                5               5.74        6
2 01:01          1 Control               10               7.74        8
3 01:01          1 Control               15              10.2        10
4 01:01          1 Control               20              11.2        11
5 01:01          1 Control               25              12.0        12
6 01:01          1 Control               30              12.4        12</code></pre>
</div>
</div>
</section>
<section id="analysis-1-whole-average-percent-coverage-figure-3a" class="level2">
<h2 class="anchored" data-anchor-id="analysis-1-whole-average-percent-coverage-figure-3a">Analysis 1: Whole Average Percent Coverage (Figure 3a)</h2>
<section id="file-description" class="level3">
<h3 class="anchored" data-anchor-id="file-description">File description</h3>
<p><strong>Perc_Coverage_Avg.csv</strong>: File containing all microglia morphology data collected using percent coverage of Iba1 stain on photomicrographs taken from brain hemispheres.</p>
<ol type="1">
<li><strong>Animal_ID</strong> – Unique identifier for individual mice.</li>
<li><strong>Treatment</strong> – Categorical variable denoting whether each mouse received control diet or Plx5622 (PLX) diet.</li>
<li><strong>Avg_percent</strong> – The percentage of the image covered by dark pixels calculated from nine photomicrographs (3 brain slices per mouse and 3 photomicrographs (of retrosplenial, somatosensory, and entorhinal cortices) per brain slice) of Iba1-stained tissue converted to binary and then averaged to produce a single value per animal.</li>
<li><strong>Perc_Cov</strong> – The averaged percent coverage converted to a decimal.</li>
</ol>
<p>Authors employed two approaches for generating percent coverage data: (1) The percent coverage values for the 9 photomicrographs were averaged to obtain a single percent coverage value per mouse, and (2) each of the 9 separate percent coverage values per mouse were retained as individual data points without averaging the values.</p>
</section>
<section id="data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="data-analysis">Data analysis</h3>
<section id="step-1-exploratory-data-analysis-of-perc_cov-treatment" class="level4">
<h4 class="anchored" data-anchor-id="step-1-exploratory-data-analysis-of-perc_cov-treatment">Step 1: Exploratory data analysis of <strong>Perc_Cov</strong> ~ <strong>Treatment</strong></h4>
<p>Explicit descriptive statistics were not conducted in this paper, but I used <code>skim()</code> to check variable types and calculate five number summaries. I also plotted the spread of the data as a histogram and visualized mean Iba1 coverage (proportion) given Treatment. I then ran a t-test comparing group means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine number of observations (nrow), number (n_unique) of Treatments</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Check variable types and 5 number summaries</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(perc_coverage_avg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">perc_coverage_avg</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">difftime</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Treatment</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: difftime</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">min</th>
<th style="text-align: left;">max</th>
<th style="text-align: left;">median</th>
<th style="text-align: right;">n_unique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Animal_ID</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">3660 secs</td>
<td style="text-align: left;">8160 secs</td>
<td style="text-align: left;">02:03:00</td>
<td style="text-align: right;">24</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Avg_percent</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">17.74</td>
<td style="text-align: right;">3.26</td>
<td style="text-align: right;">11.64</td>
<td style="text-align: right;">15.01</td>
<td style="text-align: right;">17.83</td>
<td style="text-align: right;">19.8</td>
<td style="text-align: right;">23.24</td>
<td style="text-align: left;">▃▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">Perc_Cov</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: left;">▃▇▇▇▇</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change Animal_ID variable type from time to character</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>perc_coverage_avg<span class="sc">$</span>Animal_ID <span class="ot">&lt;-</span> <span class="fu">format</span>(<span class="fu">strptime</span>(perc_coverage_avg<span class="sc">$</span>Animal_ID, </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                                               <span class="at">format =</span> <span class="st">"%H:%M:%S"</span>), </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">format =</span> <span class="st">"%H:%M:%S"</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Check Animal_ID is now a character type variable</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(perc_coverage_avg<span class="sc">$</span>Animal_ID)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> chr [1:25] "01:01:00" "01:05:00" "01:06:00" "01:07:00" "01:08:00" ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine how observations are distributed among subjects and treatments</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(perc_coverage_avg, <span class="fu">table</span>(Animal_ID, Treatment))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Treatment
Animal_ID  Control PLX
  01:01:00       1   0
  01:05:00       1   0
  01:06:00       1   0
  01:07:00       1   0
  01:08:00       1   0
  01:12:00       0   1
  01:13:00       0   1
  01:15:00       0   1
  01:16:00       0   1
  02:01:00       1   1
  02:02:00       1   0
  02:03:00       1   0
  02:04:00       1   0
  02:05:00       1   0
  02:06:00       1   0
  02:07:00       1   0
  02:08:00       1   0
  02:09:00       0   1
  02:11:00       0   1
  02:12:00       0   1
  02:13:00       0   1
  02:14:00       0   1
  02:15:00       0   1
  02:16:00       0   1</code></pre>
</div>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize Perc_Cov given Treatment</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">hist</span>(perc_coverage_avg<span class="sc">$</span>Perc_Cov)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(perc_coverage_avg, <span class="fu">aes</span>(<span class="at">x =</span> Treatment, <span class="at">y =</span> Perc_Cov)) <span class="sc">+</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> Treatment),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.06</span>)) <span class="sc">+</span> </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Treatment), <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="fl">0.0</span>, <span class="fl">0.3</span>)) <span class="sc">+</span> </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_prism</span>(<span class="st">"floral"</span>) <span class="sc">+</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_prism</span>(<span class="st">"floral"</span>) <span class="sc">+</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">y =</span> <span class="st">"prism_offset_minor"</span>) <span class="sc">+</span> </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_prism</span>(<span class="at">base_size =</span> <span class="dv">16</span>) <span class="sc">+</span> </span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel" data-layout="[50,50]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/perc_coverage_avg-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/perc_coverage_avg-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare group means</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>perc_coverage_avg_treatment <span class="ot">&lt;-</span> perc_coverage_avg <span class="sc">%&gt;%</span> </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">'Treatment'</span>, <span class="at">values_from =</span> <span class="st">'Perc_Cov'</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x =</span> perc_coverage_avg_treatment<span class="sc">$</span>Control, </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> perc_coverage_avg_treatment<span class="sc">$</span>PLX, </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  perc_coverage_avg_treatment$Control and perc_coverage_avg_treatment$PLX
t = -1.0292, df = 19.769, p-value = 0.3158
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.04116614  0.01397783
sample estimates:
mean of x mean of y 
0.1709218 0.1845160 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nice t-test table</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>t.test.results <span class="ot">&lt;-</span> <span class="fu">nice_t_test</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> perc_coverage_avg,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">response =</span> <span class="st">"Perc_Cov"</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="st">"Treatment"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">warning =</span> <span class="cn">FALSE</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Using Welch t-test (base R's default; cf. https://doi.org/10.5334/irsp.82).
For the Student t-test, use `var.equal = TRUE`. 
 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>t_table <span class="ot">&lt;-</span> <span class="fu">nice_table</span>(t.test.results)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>t_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="tabwid"><style>.cl-efe8885c{table-layout:auto;}.cl-efe446de{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-efe446e8{font-family:'Times New Roman';font-size:12pt;font-weight:normal;font-style:italic;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-efe6970e{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-efe69718{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 2;background-color:transparent;}.cl-efe69fec{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-efe69ff6{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-efe69ff7{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-efe8885c"><thead><tr style="overflow-wrap:break-word;"><th class="cl-efe69fec"><p class="cl-efe6970e"><span class="cl-efe446de">Dependent Variable</span></p></th><th class="cl-efe69fec"><p class="cl-efe6970e"><span class="cl-efe446e8">t</span></p></th><th class="cl-efe69fec"><p class="cl-efe6970e"><span class="cl-efe446e8">df</span></p></th><th class="cl-efe69fec"><p class="cl-efe6970e"><span class="cl-efe446e8">p</span></p></th><th class="cl-efe69fec"><p class="cl-efe6970e"><span class="cl-efe446e8">d</span></p></th><th class="cl-efe69fec"><p class="cl-efe6970e"><span class="cl-efe446de">95% CI</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-efe69ff6"><p class="cl-efe69718"><span class="cl-efe446de">Perc_Cov</span></p></td><td class="cl-efe69ff7"><p class="cl-efe6970e"><span class="cl-efe446de">-1.03</span></p></td><td class="cl-efe69ff7"><p class="cl-efe6970e"><span class="cl-efe446de">19.77</span></p></td><td class="cl-efe69ff7"><p class="cl-efe6970e"><span class="cl-efe446de">.316</span></p></td><td class="cl-efe69ff7"><p class="cl-efe6970e"><span class="cl-efe446de">-0.42</span></p></td><td class="cl-efe69ff7"><p class="cl-efe6970e"><span class="cl-efe446de">[-1.21, 0.38]</span></p></td></tr></tbody></table></div>
</div>
</div>
<blockquote class="blockquote">
<p>Note: The d is Cohen’s d, and the 95% CI is the confidence interval of the effect size (Cohen’s d). p is the p-value, df is degrees of freedom, and t is the t-value.</p>
</blockquote>
</section>
<section id="step-2-run-generalized-linear-mixed-model-of-perc_cov-mean-iba1-coverage-given-treatment" class="level4">
<h4 class="anchored" data-anchor-id="step-2-run-generalized-linear-mixed-model-of-perc_cov-mean-iba1-coverage-given-treatment">Step 2: Run generalized linear mixed model of <strong>Perc_Cov</strong> (Mean Iba1 coverage) given <strong>Treatment</strong></h4>
<p>Authors fit all models in the frequentist framework using the package {glmmTMB}.</p>
<blockquote class="blockquote">
<p>NOTE: to fit a model in glmmTMB:</p>
<ul>
<li>specify a model for the conditional effects, in the standard R formula notation</li>
<li>specify a model for the random effects, in the notation that is common to the {nlme} and {lme4} packages. Random effects are specified as x|g, where x is an effect and g is a grouping factor (which must be a factor variable, or a nesting of/interaction among factor variables). Formula examples:</li>
<li>1|block for a random-intercept model</li>
<li>A model of crossed random effects (block and year) would be (1|block)+(1|year).</li>
<li>choose the error distribution by specifying the family (family argument). Specify the function</li>
<li>binomial, gaussian, poisson, Gamma from base R</li>
<li>nbinom2, beta family(), betabinomial from family glmmTMB</li>
<li>choose the error distribution by specifying the family (family argument).</li>
<li>Distributions defined in base R and documented in ?family</li>
<li>Distributions defined in ?glmmTMB::family glmmTMB</li>
<li>optionally specify a zero-inflation model (ziformula argument) with fixed and/or random effects</li>
<li>optionally specify a dispersion model with fixed effects</li>
</ul>
</blockquote>
<p>Components of generalized linear mixed model of <strong>Perc_Cov</strong> given <strong>Treatment</strong></p>
<ul>
<li>Fixed effect for <strong>Treatment</strong></li>
<li>Beta error distribution, as <strong>Perc_Cov</strong> values are bounded between 0 and 1</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>perc_cov_avg_model <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(Perc_Cov <span class="sc">~</span> Treatment, </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family =</span> <span class="fu">beta_family</span>(<span class="at">link =</span> <span class="st">"logit"</span>),</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data =</span> perc_coverage_avg)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(perc_cov_avg_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: beta  ( logit )
Formula:          Perc_Cov ~ Treatment
Data: perc_coverage_avg

     AIC      BIC   logLik deviance df.resid 
   -95.4    -91.8     50.7   -101.4       22 


Dispersion parameter for beta family ():  141 

Conditional model:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -1.57444    0.06159  -25.56   &lt;2e-16 ***
TreatmentPLX  0.08311    0.08746    0.95    0.342    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Formula <span class="math display">\[logit(\pi_i) = -1.57444 + 0.08311 \times {Treatment}\]</span></p>
<p>The coefficient for treatment is positive but not significantly different from 0. Thus, the treatment does not increase the log(odds ratio) of Perc_Cov (i.e., this measure of microglia reactivity is not significantly increased by the treatment). In this model, for every one unit change in treatment (0 for control, 1 for PLX), the log odds of Perc_Cov increases by 0.08311.</p>
</section>
<section id="step-3-obtain-inferential-statistics-using-emmeans" class="level4">
<h4 class="anchored" data-anchor-id="step-3-obtain-inferential-statistics-using-emmeans">Step 3: Obtain inferential statistics using {emmeans}</h4>
<p>Authors used {emmeans} to obtain coefficient estimates (β) and their 95% confidence intervals, differences between predicted conditional means (∆), effect sizes (d), and p-values following Tukey’s adjustments for multiple comparisons</p>
<p>Differences between predicted conditional means (∆) are reported in %, which I interpreted to be the absolute value in units of the response variable (% mean Iba1 coverage). I reported my estimate of the difference in units of proportion, as graphed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model converted to log scale, want results on response scale</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Get point estimates (estimated marginal means) and 95% CIs </span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>emm_r <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(perc_cov_avg_model, <span class="sc">~</span> Treatment,  <span class="at">component =</span> <span class="st">"response"</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the point estimates and their 95% confidence intervals</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>(estimates_r <span class="ot">&lt;-</span> <span class="fu">summary</span>(emm_r, <span class="at">type =</span> <span class="st">"response"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Treatment emmean      SE  df asymp.LCL asymp.UCL
 Control    0.172 0.00875 Inf     0.154     0.189
 PLX        0.184 0.00936 Inf     0.165     0.202

Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the pairwise comparisons</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate = difference between predicted conditional means (∆) and p-value</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># negative value if control &lt; PLX</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>(pairwise_r <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm_r, <span class="at">adjust =</span> <span class="st">"tukey"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast      estimate     SE  df z.ratio p.value
 Control - PLX  -0.0121 0.0128 Inf  -0.949  0.3424</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To obtain effect size using pooled standard deviation from model, </span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># need difference between means on log scale</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(perc_cov_avg_model, <span class="sc">~</span> Treatment)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>pairwise <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>(differences <span class="ot">&lt;-</span> <span class="fu">summary</span>(pairwise))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast      estimate     SE  df z.ratio p.value
 Control - PLX  -0.0831 0.0875 Inf  -0.950  0.3420

Results are given on the log odds ratio (not the response) scale. </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># effect size (d)</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># d = Difference between means / Pooled standard deviation</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>(effect_size <span class="ot">&lt;-</span> <span class="fu">eff_size</span>(emm, </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">sigma =</span> <span class="fu">sigma</span>(perc_cov_avg_model),</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">edf =</span> <span class="fu">df.residual</span>(perc_cov_avg_model)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast      effect.size       SE  df asymp.LCL asymp.UCL
 Control - PLX    -0.00059 0.000627 Inf  -0.00182  0.000639

sigma used for effect sizes: 140.9 
Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># reporting absolute value of ∆ and d below</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="step-4-visualize-mean-iba1-coverage-treatment" class="level5">
<h5 class="anchored" data-anchor-id="step-4-visualize-mean-iba1-coverage-treatment">Step 4: Visualize Mean Iba1 coverage ~ treatment</h5>
<p>Scatter dot plot with estimated means and 95% CI</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define custom graph colors</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>gray_scale <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#A0A0A4"</span>, <span class="st">"#808080"</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>base <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(perc_coverage_avg, <span class="fu">aes</span>(<span class="at">x =</span> Treatment)) <span class="sc">+</span> </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> Perc_Cov, <span class="at">color =</span> <span class="fu">factor</span>(Treatment)),</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.06</span>),</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">1</span>,</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="at">data =</span> estimates_r,</span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">aes</span>(<span class="at">y =</span> emmean, <span class="at">ymin =</span> asymp.LCL, <span class="at">ymax =</span> asymp.UCL),</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">size =</span> <span class="fl">0.4</span>) <span class="sc">+</span>  <span class="co"># Add point estimates and confidence intervals</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data =</span> estimates_r, <span class="fu">aes</span>(<span class="at">y =</span> emmean, <span class="at">ymin =</span> asymp.LCL, <span class="at">ymax =</span> asymp.UCL), </span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), </span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.4</span>,</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span> <span class="co"># Add confidence intervals bars</span></span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="fl">0.0</span>, <span class="fl">0.3</span>)) <span class="sc">+</span></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Mean Iba1 Coverage (%)"</span>) <span class="sc">+</span></span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Control"</span>, <span class="st">"Treatment"</span>)) <span class="sc">+</span></span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="cn">NULL</span>)</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Need to update p.value by hand</span></span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a><span class="co"># add p_values</span></span>
<span id="cb41-23"><a href="#cb41-23" aria-hidden="true" tabindex="-1"></a>p_vals <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb41-24"><a href="#cb41-24" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>group1, <span class="sc">~</span>group2, <span class="sc">~</span>p.value,   <span class="sc">~</span>y.position,</span>
<span id="cb41-25"><a href="#cb41-25" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Control"</span>,   <span class="st">"PLX"</span>,     <span class="fl">0.34</span>, <span class="fl">0.295</span></span>
<span id="cb41-26"><a href="#cb41-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb41-27"><a href="#cb41-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-28"><a href="#cb41-28" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> base <span class="sc">+</span> </span>
<span id="cb41-29"><a href="#cb41-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> gray_scale) <span class="sc">+</span></span>
<span id="cb41-30"><a href="#cb41-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_prism</span>(<span class="at">base_size =</span> <span class="dv">16</span>,</span>
<span id="cb41-31"><a href="#cb41-31" aria-hidden="true" tabindex="-1"></a>              <span class="at">base_fontface =</span> <span class="st">"plain"</span>,</span>
<span id="cb41-32"><a href="#cb41-32" aria-hidden="true" tabindex="-1"></a>              <span class="at">base_family =</span> <span class="st">"Arial"</span>) <span class="sc">+</span> </span>
<span id="cb41-33"><a href="#cb41-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb41-34"><a href="#cb41-34" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">linewidth =</span> <span class="fl">0.2</span>),</span>
<span id="cb41-35"><a href="#cb41-35" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_line</span>(<span class="at">linewidth =</span> <span class="fl">0.2</span>),</span>
<span id="cb41-36"><a href="#cb41-36" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.length =</span> <span class="fu">unit</span>(<span class="fl">0.1</span>, <span class="st">"cm"</span>),</span>
<span id="cb41-37"><a href="#cb41-37" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb41-38"><a href="#cb41-38" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">vjust=</span><span class="fl">1.5</span>), <span class="co"># move labels closer to axis</span></span>
<span id="cb41-39"><a href="#cb41-39" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb41-40"><a href="#cb41-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_pvalue</span>(p_vals, <span class="at">label =</span> <span class="st">"p = {p.value}"</span>, <span class="at">tip.length =</span> <span class="dv">0</span>, <span class="at">label.size =</span> <span class="dv">4</span>, <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.3</span>) <span class="co"># added p-value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Save plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"ERC_fig3a.png"</span>, </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">width =</span> <span class="dv">4</span>, <span class="at">height =</span> <span class="fl">3.5</span>, <span class="at">units =</span> <span class="st">"in"</span>,</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">path =</span> <span class="st">"images/"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<p>NOTE: Comparison of Results shown at the end of Analysis 2</p>
</blockquote>
<div>

</div>
<div class="cell quarto-layout-panel" data-layout="[55,45]">

</div>
</section>
</section>
</section>
</section>
<section id="analysis-2-whole-percent-coverage" class="level2">
<h2 class="anchored" data-anchor-id="analysis-2-whole-percent-coverage">Analysis 2: Whole Percent Coverage</h2>
<section id="file-description-1" class="level3">
<h3 class="anchored" data-anchor-id="file-description-1">File description</h3>
<p><strong>Perc_Coverage.csv</strong>: File containing all microglia morphology data collected using percent coverage of Iba1 stain on photomicrographs taken from brain hemispheres.</p>
<ol type="1">
<li><strong>Animal_ID</strong> – Unique identifier for individual mice.</li>
<li><strong>Treatment</strong> – Categorical variable denoting whether each mouse received c ontrol diet or Plx5622 (PLX) diet.</li>
<li><strong>Coverage</strong> – The percentage of the image covered by dark pixels calculated from photomicrographs of Iba1-stained tissue converted to binary.</li>
<li><strong>Perc_Cov</strong> – The percent coverage converted to a decimal.</li>
</ol>
</section>
<section id="data-wrangling" class="level3">
<h3 class="anchored" data-anchor-id="data-wrangling">Data wrangling</h3>
<p>Clean up data frame for hierarchical generalized linear mixed model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change Animal_ID variable type from time to character</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>perc_coverage<span class="sc">$</span>Animal_ID <span class="ot">&lt;-</span> <span class="fu">format</span>(<span class="fu">strptime</span>(perc_coverage<span class="sc">$</span>Animal_ID, </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">format =</span> <span class="st">"%H:%M:%S"</span>), </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">format =</span> <span class="st">"%H:%M:%S"</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Check binned number of cells per subject in perc_coverage</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>cells <span class="ot">&lt;-</span> perc_coverage <span class="sc">%&gt;%</span> </span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Animal_ID, Treatment) <span class="sc">%&gt;%</span> </span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">binned_cells =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Animal_ID'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add binned number of cells to perc_coverage</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>perc_coverage <span class="ot">&lt;-</span> <span class="fu">full_join</span>(perc_coverage, cells)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(Animal_ID, Treatment)`</code></pre>
</div>
</div>
</section>
<section id="data-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="data-analysis-1">Data Analysis</h3>
<section id="step-1-exploratory-data-analysis-of-perc_cov-treatment-1" class="level4">
<h4 class="anchored" data-anchor-id="step-1-exploratory-data-analysis-of-perc_cov-treatment-1">Step 1: Exploratory data analysis of <strong>Perc_Cov</strong> ~ <strong>Treatment</strong></h4>
<p>Explicit descriptive statistics were not conducted in this paper, but I used <code>skim()</code> to check variable types and calculate five number summaries. I also plotted the spread of the data as a histogram and visualized Iba1 coverage (proportion, <strong>Perc_Cov</strong>) given <strong>Treatment</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine number of observations (nrow), number (n_unique) of Treatments</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Check variable types and 5 number summaries</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(perc_coverage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">perc_coverage</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">225</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Animal_ID</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Treatment</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Coverage</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">17.74</td>
<td style="text-align: right;">4.59</td>
<td style="text-align: right;">6.59</td>
<td style="text-align: right;">14.89</td>
<td style="text-align: right;">17.92</td>
<td style="text-align: right;">21.12</td>
<td style="text-align: right;">29.14</td>
<td style="text-align: left;">▂▅▇▆▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">Perc_Cov</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.15</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">0.21</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: left;">▂▅▇▆▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">binned_cells</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: left;">▁▁▇▁▁</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine how observations are distributed among subjects and treatments</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(perc_coverage, <span class="fu">table</span>(Animal_ID, Treatment))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Treatment
Animal_ID  Control PLX
  01:01:00       9   0
  01:05:00       9   0
  01:06:00       9   0
  01:07:00       9   0
  01:08:00       9   0
  01:12:00       0   9
  01:13:00       0   9
  01:15:00       0   9
  01:16:00       0   9
  02:01:00       9   9
  02:02:00       9   0
  02:03:00       9   0
  02:04:00       9   0
  02:05:00       9   0
  02:06:00       9   0
  02:07:00       9   0
  02:08:00       9   0
  02:09:00       0   9
  02:11:00       0   9
  02:12:00       0   9
  02:13:00       0   9
  02:14:00       0   9
  02:15:00       0   9
  02:16:00       0   9</code></pre>
</div>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize Perc_Cov given Treatment</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">hist</span>(perc_coverage<span class="sc">$</span>Perc_Cov)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(perc_coverage, <span class="fu">aes</span>(<span class="at">x =</span> Treatment, <span class="at">y =</span> Perc_Cov)) <span class="sc">+</span> </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> Treatment),</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.07</span>)) <span class="sc">+</span> </span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Treatment), <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="fl">0.0</span>, <span class="fl">0.3</span>)) <span class="sc">+</span> </span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_prism</span>(<span class="st">"floral"</span>) <span class="sc">+</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_prism</span>(<span class="st">"floral"</span>) <span class="sc">+</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">y =</span> <span class="st">"prism_offset_minor"</span>) <span class="sc">+</span> </span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_prism</span>(<span class="at">base_size =</span> <span class="dv">16</span>) <span class="sc">+</span> </span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel" data-layout="[50,50]">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/perc_coverage-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="images/perc_coverage-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</section>
<section id="step-2-run-hierarchical-generalized-linear-mixed-model-of-perc_cov-iba1-coverage-given-treatment" class="level4">
<h4 class="anchored" data-anchor-id="step-2-run-hierarchical-generalized-linear-mixed-model-of-perc_cov-iba1-coverage-given-treatment">Step 2: Run hierarchical generalized linear mixed model of <strong>Perc_Cov</strong> (Iba1 coverage) given <strong>Treatment</strong></h4>
<ul>
<li>Include fixed effect for <strong>Treatment</strong></li>
<li>Include random intercepts for <strong>Animal_ID</strong>, individual mouse, <em>crossed with</em> random intercepts for <strong>binned_cells</strong>, the binned number of cells that were used to obtain the outcome value (n = 9 data points per mouse).
<ul>
<li>Random effects structure accommodated…</li>
<li>hierarchical clustering of multiple aggregate data points from each mouse and</li>
<li>the possibility that the number of cells used to calculate a given value might introduce unaccounted for variation.</li>
</ul></li>
<li>Beta error distribution, as <strong>Perc_Cov</strong> values are bounded between 0 and 1</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>perc_cov_model <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(Perc_Cov <span class="sc">~</span> Treatment <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>Animal_ID) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>binned_cells),</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family =</span> <span class="fu">beta_family</span>(<span class="at">link=</span><span class="st">"logit"</span>),</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data =</span> perc_coverage)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(perc_cov_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Family: beta  ( logit )
Formula:          Perc_Cov ~ Treatment + (1 | Animal_ID) + (1 | binned_cells)
Data: perc_coverage

     AIC      BIC   logLik deviance df.resid 
  -796.2   -779.1    403.1   -806.2      220 

Random effects:

Conditional model:
 Groups       Name        Variance  Std.Dev. 
 Animal_ID    (Intercept) 4.738e-02 2.177e-01
 binned_cells (Intercept) 1.473e-10 1.214e-05
Number of obs: 225, groups:  Animal_ID, 24; binned_cells, 1

Dispersion parameter for beta family ():  107 

Conditional model:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -1.65878    0.06413  -25.86  &lt; 2e-16 ***
TreatmentPLX  0.24164    0.08786    2.75  0.00595 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Random intercepts do not seem to add explanatory power (very low amount of Variance in response variable explained)</p>
<p>Formula <span class="math display">\[logit(\pi_i) = -1.65878 + 0.24164 \times {Treatment}\]</span></p>
<p>The coefficient for treatment is positive and is significantly different from 0. Thus, the treatment increases the log(odds ratio) of Perc_Cov (i.e., this measure of microglia reactivity is significantly increased by the treatment). In this model, for every one unit change in treatment (0 for control, 1 for PLX), the log odds of Perc_Cov increases by 0.24164.</p>
</section>
<section id="step-3-obtain-inferential-statistics-using-emmeans-1" class="level4">
<h4 class="anchored" data-anchor-id="step-3-obtain-inferential-statistics-using-emmeans-1">Step 3: Obtain inferential statistics using {emmeans}</h4>
<p>Authors used {emmeans} to obtain coefficient estimates (β) and their 95% confidence intervals, differences between predicted conditional means (∆), effect sizes (d), and p-values following Tukey’s adjustments for multiple comparisons</p>
<p>Differences between predicted conditional means (∆) are reported in %, which I interpreted to be the absolute value in units of the response variable (mean Iba1 coverage). I reported my estimate of the difference in units of proportion.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model converted to log scale, want results on response scale</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Get point estimates (estimated marginal means) and 95% CIs </span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>emm_r <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(perc_cov_model, <span class="sc">~</span> Treatment,  <span class="at">component =</span> <span class="st">"response"</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the point estimates and their 95% confidence intervals</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>(estimates_r <span class="ot">&lt;-</span> <span class="fu">summary</span>(emm_r, <span class="at">type =</span> <span class="st">"response"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Treatment emmean      SE  df asymp.LCL asymp.UCL
 Control    0.160 0.00862 Inf     0.143     0.177
 PLX        0.195 0.01027 Inf     0.175     0.215

Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the pairwise comparisons</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate = difference between predicted conditional means (∆) and p-value</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="co"># negative if control &lt; PLX</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>(pairwise_r <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm_r, <span class="at">adjust =</span> <span class="st">"tukey"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast      estimate     SE  df z.ratio p.value
 Control - PLX  -0.0352 0.0129 Inf  -2.734  0.0062</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To obtain effect size using pooled standard deviation from model, </span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="co"># need difference between means on log scale</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(perc_cov_model, <span class="sc">~</span> Treatment)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>pairwise <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>(differences <span class="ot">&lt;-</span> <span class="fu">summary</span>(pairwise))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast      estimate     SE  df z.ratio p.value
 Control - PLX   -0.242 0.0879 Inf  -2.750  0.0060

Results are given on the log odds ratio (not the response) scale. </code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># effect size (d)</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="co"># d = Difference between means / Pooled standard deviation</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>(effect_size <span class="ot">&lt;-</span> <span class="fu">eff_size</span>(emm, </span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">sigma =</span> <span class="fu">sigma</span>(perc_cov_model),</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">edf =</span> <span class="fu">df.residual</span>(perc_cov_model)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>                         )</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast      effect.size       SE  df asymp.LCL asymp.UCL
 Control - PLX    -0.00226 0.000827 Inf  -0.00388 -0.000635

sigma used for effect sizes: 107.1 
Confidence level used: 0.95 </code></pre>
</div>
</div>
<section id="step-4-visualize-iba1-coverage-treatment" class="level5">
<h5 class="anchored" data-anchor-id="step-4-visualize-iba1-coverage-treatment">Step 4: Visualize Iba1 coverage ~ treatment</h5>
<p>Scatter dot plot with estimated means and 95% CI</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set plot size</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repr.plot.width =</span> <span class="dv">2</span>, <span class="at">repr.plot.height =</span><span class="dv">4</span>)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="co"># define custom graph colors</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>gray_scale <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#A0A0A4"</span>, <span class="st">"#808080"</span>)</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>base <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(perc_coverage, <span class="fu">aes</span>(<span class="at">x =</span> Treatment)) <span class="sc">+</span> </span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> Perc_Cov, <span class="at">color =</span> <span class="fu">factor</span>(Treatment)),</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.07</span>),</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">1</span>,</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="at">data =</span> estimates_r,</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">aes</span>(<span class="at">y =</span> emmean, <span class="at">ymin =</span> asymp.LCL, <span class="at">ymax =</span> asymp.UCL),</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>                  <span class="at">size =</span> <span class="fl">0.4</span>) <span class="sc">+</span>  <span class="co"># Add point estimates and confidence intervals</span></span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="at">data =</span> estimates_r, <span class="fu">aes</span>(<span class="at">y =</span> emmean, <span class="at">ymin =</span> asymp.LCL, <span class="at">ymax =</span> asymp.UCL), </span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>                <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), </span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.4</span>,</span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>                <span class="at">linewidth =</span> <span class="fl">0.7</span>) <span class="sc">+</span> <span class="co"># Add confidence intervals bars</span></span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="fl">0.0</span>, <span class="fl">0.3</span>)) <span class="sc">+</span></span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Iba1 Coverage (%)"</span>) <span class="sc">+</span></span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Control"</span>, <span class="st">"Treatment"</span>)) <span class="sc">+</span></span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="cn">NULL</span>)</span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Need to update p.value by hand</span></span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a><span class="co"># add p_values</span></span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a>p_vals <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span>group1, <span class="sc">~</span>group2, <span class="sc">~</span>p.value,   <span class="sc">~</span>y.position,</span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Control"</span>,   <span class="st">"PLX"</span>,     <span class="fl">0.006</span>, <span class="fl">0.295</span></span>
<span id="cb61-29"><a href="#cb61-29" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb61-30"><a href="#cb61-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-31"><a href="#cb61-31" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> base <span class="sc">+</span> </span>
<span id="cb61-32"><a href="#cb61-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> gray_scale) <span class="sc">+</span></span>
<span id="cb61-33"><a href="#cb61-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_prism</span>(<span class="at">base_size =</span> <span class="dv">16</span>,</span>
<span id="cb61-34"><a href="#cb61-34" aria-hidden="true" tabindex="-1"></a>              <span class="at">base_fontface =</span> <span class="st">"plain"</span>,</span>
<span id="cb61-35"><a href="#cb61-35" aria-hidden="true" tabindex="-1"></a>              <span class="at">base_family =</span> <span class="st">"Arial"</span>) <span class="sc">+</span> </span>
<span id="cb61-36"><a href="#cb61-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb61-37"><a href="#cb61-37" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">linewidth =</span> <span class="fl">0.2</span>),</span>
<span id="cb61-38"><a href="#cb61-38" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_line</span>(<span class="at">linewidth =</span> <span class="fl">0.2</span>),</span>
<span id="cb61-39"><a href="#cb61-39" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.length =</span> <span class="fu">unit</span>(<span class="fl">0.1</span>, <span class="st">"cm"</span>),</span>
<span id="cb61-40"><a href="#cb61-40" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb61-41"><a href="#cb61-41" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">vjust=</span><span class="fl">1.5</span>), <span class="co"># move labels closer to axis</span></span>
<span id="cb61-42"><a href="#cb61-42" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb61-43"><a href="#cb61-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_pvalue</span>(p_vals, <span class="at">label =</span> <span class="st">"p = {p.value}"</span>, <span class="at">tip.length =</span> <span class="dv">0</span>, <span class="at">label.size =</span> <span class="dv">4</span>, <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.3</span>) <span class="co"># added p-value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Save plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"ERC_fig3b.png"</span>, </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">width =</span> <span class="dv">4</span>, <span class="at">height =</span> <span class="fl">3.5</span>, <span class="at">units =</span> <span class="st">"in"</span>,</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">path =</span> <span class="st">"images/"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
</section>
<section id="analysis-1-and-2-comparison-of-results-figure-3a-b" class="level2">
<h2 class="anchored" data-anchor-id="analysis-1-and-2-comparison-of-results-figure-3a-b">Analysis 1 and 2: Comparison of Results (Figure 3a-b)</h2>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row quarto-layout-valign-bottom">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig3a.png" class="img-fluid figure-img"></p>
<figcaption>Paper: p-value = 0.35, Mean ∆ = 1.2%, d = 0.0006</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ERC_fig3a.png" class="img-fluid figure-img"></p>
<figcaption>Mine: p-value = 0.34, Mean ∆ = 0.012, d = 0.0006</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-bottom">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig3b.png" class="img-fluid figure-img"></p>
<figcaption>Paper: p-value = 0.006, Mean ∆ = 3.5%, d = 0.002</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ERC_fig3b.png" class="img-fluid figure-img"></p>
<figcaption>Mine: p-value = 0.006, Mean ∆ = 0.035, d = 0.002</figcaption>
</figure>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Figure 3a. Full photomicrograph analyses of microglial morphology were not sensitive to differences between control and treatments groups. Mean percent coverage of Iba1 staining per animal (3 brain slices per mouse and 3 photomicrographs per brain slice were used) is shown as individual data points. Treatment n = 12 mice, Control n = 13 mice. Results are presented as point estimates with 95% confidence intervals, which were estimated from mixed effects model with beta error distribution.</p>
<p>Figure 3b. Photomicrograph-specific (unaveraged) percent coverage detected significantly more Iba1 staining in the treatment group compared to controls. Percent coverage of Iba1 staining, with multiple data points per subject, is shown as individual data points. Treatment n = 108 images (12 mice, 9 images/mouse), Control n = 117 images (13 mice, 9 images/mouse). Results are presented as point estimates with 95% confidence intervals, which were estimated from mixed effects model with beta error distribution.</p>
<p>NOTE: Mean Iba1 coverage analyzed/graphed as <em>proportion</em> of coverage, while mean ∆ appears to be reported by authors as |<em>percentage</em> of coverage|.</p>
</blockquote>
</section>
<section id="analysis-3-single-cell-sholl-analysis-bonus" class="level2">
<h2 class="anchored" data-anchor-id="analysis-3-single-cell-sholl-analysis-bonus">Analysis 3: Single Cell Sholl Analysis (bonus)</h2>
<blockquote class="blockquote">
<p>NOTE: I attempted to recreate their sholl analysis, but ran into some problems. I already included two descriptive statistical analyses, visualizations, and inferential statistical analyses, so this is bonus content.</p>
</blockquote>
<section id="file-description-2" class="level3">
<h3 class="anchored" data-anchor-id="file-description-2">File description</h3>
<p><strong>Sholl_Data.csv</strong>: File containing all microglia morphology data collected using Sholl analysis of Iba1-stained microglia randomly selected and isolated from photomicrographs taken from brain hemispheres.</p>
<ol type="1">
<li><strong>Animal_ID</strong> – Unique identifier for individual mice.</li>
<li><strong>Cohort</strong> – Categorical variable denoting the experimental cohort each mouse was in.</li>
<li><strong>Treatment</strong> – Categorical variable denoting whether each mouse received control diet or Plx5622 (PLX) diet.</li>
<li><strong>Distance(um)</strong> – Continuous variable of the Sholl circle distance from the microglial cell soma (μm).</li>
<li><strong>avg_intersection_n</strong> – Continuous variable of the average number of times a microglial branch intersected a Sholl circle.</li>
<li><strong>intern_C</strong> – Continuous variable of the average number of times a microglial branch intersected a Sholl circle rounded to the nearest whole number.</li>
</ol>
</section>
<section id="data-analysis-2" class="level3">
<h3 class="anchored" data-anchor-id="data-analysis-2">Data analysis</h3>
</section>
<section id="data-wrangling-1" class="level3">
<h3 class="anchored" data-anchor-id="data-wrangling-1">Data wrangling</h3>
<p>Clean up data frame for hierarchical generalized linear mixed model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change Animal_ID variable type from time to character</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>sholl_data<span class="sc">$</span>Animal_ID <span class="ot">&lt;-</span> <span class="fu">format</span>(<span class="fu">strptime</span>(sholl_data<span class="sc">$</span>Animal_ID, </span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>                                           <span class="at">format =</span> <span class="st">"%H:%M:%S"</span>), </span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">format =</span> <span class="st">"%H:%M:%S"</span>)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Check binned number of cells per subject in sholl_data</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>cells <span class="ot">&lt;-</span> sholl_data <span class="sc">%&gt;%</span> </span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Animal_ID, Treatment) <span class="sc">%&gt;%</span> </span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">binned_cells =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Animal_ID'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add binned number of cells to sholl_data</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>sholl_data <span class="ot">&lt;-</span> <span class="fu">full_join</span>(sholl_data, cells)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(Animal_ID, Treatment)`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename distance variable</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>sholl_data <span class="ot">&lt;-</span> sholl_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">distance =</span> <span class="st">"Distance(um)"</span>)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Make distance a factor</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>sholl_data<span class="sc">$</span>distance <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(sholl_data<span class="sc">$</span>distance)</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(sholl_data<span class="sc">$</span>distance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Factor w/ 25 levels "5","10","15",..: 1 2 3 4 5 6 7 8 9 10 ...</code></pre>
</div>
</div>
</section>
<section id="data-analysis-3" class="level3">
<h3 class="anchored" data-anchor-id="data-analysis-3">Data Analysis</h3>
<section id="step-1-exploratory-data-analysis-of-intern_c-distance-treatment" class="level4">
<h4 class="anchored" data-anchor-id="step-1-exploratory-data-analysis-of-intern_c-distance-treatment">Step 1: Exploratory data analysis of <strong>intern_C</strong> ~ <strong>distance</strong> + <strong>Treatment</strong></h4>
<p>Explicit descriptive statistics were not conducted in this paper, but I used <code>skim()</code> to check variable types and calculate five number summaries. I also plotted the spread of the data as a histogram and visualized average Sholl intersections (rounded count, <strong>intern_C</strong>) by <strong>distance</strong> given <strong>Treatment</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine number of observations (nrow), number (n_unique) of Treatments</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Check variable types and 5 number summaries</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(sholl_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">sholl_data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">599</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Animal_ID</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Treatment</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">distance</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;">5: 24, 10: 24, 15: 24, 20: 24</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cohort</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.62</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: left;">▅▁▁▁▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">avg_intersection_n</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.72</td>
<td style="text-align: right;">4.80</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: right;">2.89</td>
<td style="text-align: right;">8.87</td>
<td style="text-align: right;">16.37</td>
<td style="text-align: left;">▇▂▂▂▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">intern_C</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4.69</td>
<td style="text-align: right;">4.83</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">9.00</td>
<td style="text-align: right;">16.00</td>
<td style="text-align: left;">▇▂▂▂▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">binned_cells</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">24.96</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">25.00</td>
<td style="text-align: right;">25.00</td>
<td style="text-align: right;">25.00</td>
<td style="text-align: right;">25.00</td>
<td style="text-align: left;">▁▁▁▁▇</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine how observations are distributed among subjects and treatments</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(sholl_data, <span class="fu">table</span>(Animal_ID, Treatment))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Treatment
Animal_ID  Control PLX
  01:01:00      25   0
  01:05:00      25   0
  01:06:00      25   0
  01:07:00      25   0
  01:08:00      25   0
  01:12:00       0  25
  01:13:00       0  25
  01:15:00       0  25
  01:16:00       0  25
  02:01:00      25  25
  02:02:00      25   0
  02:03:00      25   0
  02:04:00      25   0
  02:05:00      25   0
  02:06:00      25   0
  02:07:00      25   0
  02:08:00      25   0
  02:09:00       0  24
  02:11:00       0  25
  02:12:00       0  25
  02:13:00       0  25
  02:15:00       0  25
  02:16:00       0  25</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize intern_C by Distance(um) given Treatment</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sholl_data, <span class="fu">aes</span>(<span class="at">x =</span> distance, <span class="at">y =</span> intern_C, <span class="at">group =</span> Treatment)) <span class="sc">+</span> </span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> Treatment),</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">1</span>,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>),</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_prism</span>(<span class="st">"colorblind_safe"</span>) <span class="sc">+</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_prism</span>(<span class="at">base_size =</span> <span class="dv">16</span>,</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">base_fontface =</span> <span class="st">"plain"</span>,</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">base_family =</span> <span class="st">"Arial"</span>) <span class="sc">+</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="fl">0.85</span>, <span class="fl">0.9</span>),</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">linewidth =</span> <span class="fl">0.2</span>),</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_line</span>(<span class="at">linewidth =</span> <span class="fl">0.2</span>),</span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">angle =</span> <span class="dv">45</span>),</span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.length =</span> <span class="fu">unit</span>(<span class="fl">0.1</span>, <span class="st">"cm"</span>))</span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a>p1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/sholl-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-2-attempt-to-run-hierarchical-generalized-linear-mixed-model-of-average-sholl-intersections-rounded-count-intern_c-by-distance-given-treatment." class="level4">
<h4 class="anchored" data-anchor-id="step-2-attempt-to-run-hierarchical-generalized-linear-mixed-model-of-average-sholl-intersections-rounded-count-intern_c-by-distance-given-treatment.">Step 2: Attempt to run hierarchical generalized linear mixed model of average Sholl intersections (rounded count, <strong>intern_C</strong>) by <strong>distance</strong> given <strong>Treatment</strong>.</h4>
<p>This was very hard. I have not yet figured out how they got their point estimates / if this model is the same as theirs.</p>
<ul>
<li>Include fixed effect for
<ul>
<li><strong>distance</strong>, distance from cell body</li>
<li><strong>Treatment</strong></li>
<li>two-way interaction between <strong>Treatment</strong> and <strong>distance</strong></li>
</ul></li>
<li>Include random intercepts for <strong>Animal_ID</strong>, individual mouse
<ul>
<li>for hierarchical clustering of multiple data points from each mouse (n = 25 distances at which the mean number of intersections was calculated per mouse)</li>
</ul></li>
<li>Negative-binomial error distribution, as <strong>intern_C</strong> is an overdispersed count variable</li>
</ul>
<p>Authors also stated that they included a natural cubic spline on <strong>distance</strong>, as they expected this effect to be nonlinear. I think this can be added to the model using {splines} and including a main effect of <code>ns(Distance(um), 3)</code></p>
<p><em>Not working after converting distance to a factor…</em></p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># base model, not running with distance as factor</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>sholl_model <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(intern_C <span class="sc">~</span> distance <span class="sc">*</span> Treatment <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>Animal_ID),</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family =</span> <span class="fu">nbinom2</span>(), <span class="co"># quadratic</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data =</span> sholl_data)</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sholl_model)</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a><span class="co"># modeling nonlinear relationship</span></span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(splines)</span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>sholl_model_sp <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(intern_C <span class="sc">~</span> distance <span class="sc">*</span> Treatment <span class="sc">+</span> <span class="fu">ns</span>(distance, <span class="dv">3</span>) <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>Animal_ID),</span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>                          <span class="at">family =</span> <span class="fu">nbinom2</span>(<span class="at">link =</span> <span class="st">"log"</span>), <span class="co"># quadratic</span></span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data =</span> sholl_data)</span>
<span id="cb73-12"><a href="#cb73-12" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sholl_model_sp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="step-3-attempt-to-obtain-inferential-statistics-using-emmeans" class="level4">
<h4 class="anchored" data-anchor-id="step-3-attempt-to-obtain-inferential-statistics-using-emmeans">Step 3: Attempt to obtain inferential statistics using {emmeans}</h4>
<p>Authors used {emmeans} to obtain coefficient estimates (β) and their 95% confidence intervals, differences between predicted conditional means (∆), effect sizes (d), and p-values following Tukey’s adjustments for multiple comparisons</p>
<p><em>This is not right, am not getting values across multiple distances</em></p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model converted to log scale, want results on response scale</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Get point estimates (estimated marginal means) and 95% CIs </span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>emm_r <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(sholl_model, <span class="sc">~</span> Treatment, <span class="at">var =</span> <span class="st">"distance"</span>,  <span class="at">component =</span> <span class="st">"response"</span>)</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the point estimates and their 95% confidence intervals</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>(estimates_r <span class="ot">&lt;-</span> <span class="fu">summary</span>(emm_r, <span class="at">type =</span> <span class="st">"response"</span>))</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the pairwise comparisons</span></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate = difference between predicted conditional means (∆) and p-value</span></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a><span class="co"># negative if control &lt; PLX</span></span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>(pairwise_r <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm_r, <span class="at">adjust =</span> <span class="st">"tukey"</span>))</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a><span class="co"># To obtain effect size using pooled standard deviation from model, </span></span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a><span class="co"># need difference between means on log scale</span></span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(sholl_model, <span class="fu">c</span>(<span class="st">"Treatment"</span>, <span class="st">"distance"</span>))</span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a>pairwise <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span>
<span id="cb74-18"><a href="#cb74-18" aria-hidden="true" tabindex="-1"></a>(differences <span class="ot">&lt;-</span> <span class="fu">summary</span>(pairwise))</span>
<span id="cb74-19"><a href="#cb74-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-20"><a href="#cb74-20" aria-hidden="true" tabindex="-1"></a><span class="co"># effect size (d)</span></span>
<span id="cb74-21"><a href="#cb74-21" aria-hidden="true" tabindex="-1"></a><span class="co"># d = Difference between means / Pooled standard deviation</span></span>
<span id="cb74-22"><a href="#cb74-22" aria-hidden="true" tabindex="-1"></a>(effect_size <span class="ot">&lt;-</span> <span class="fu">eff_size</span>(emm, </span>
<span id="cb74-23"><a href="#cb74-23" aria-hidden="true" tabindex="-1"></a>                         <span class="at">sigma =</span> <span class="fu">sigma</span>(sholl_model),</span>
<span id="cb74-24"><a href="#cb74-24" aria-hidden="true" tabindex="-1"></a>                         <span class="at">edf =</span> <span class="fu">df.residual</span>(sholl_model)</span>
<span id="cb74-25"><a href="#cb74-25" aria-hidden="true" tabindex="-1"></a>                         )</span>
<span id="cb74-26"><a href="#cb74-26" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="step-4-running-alternative-model-of-average-sholl-intersections-rounded-count-intern_c-by-distance-given-treatment." class="level5">
<h5 class="anchored" data-anchor-id="step-4-running-alternative-model-of-average-sholl-intersections-rounded-count-intern_c-by-distance-given-treatment.">Step 4: Running alternative model of average Sholl intersections (rounded count, <strong>intern_C</strong>) by <strong>distance</strong> given <strong>Treatment</strong>.</h5>
<p>There is a significant interaction between <strong>distance</strong> and <strong>Treatment</strong>, so restricting comparisons to Treatment within each distance is just a starting point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># non-linear modeling</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>sholl_model <span class="ot">&lt;-</span> nlme<span class="sc">::</span><span class="fu">lme</span>(intern_C <span class="sc">~</span> distance <span class="sc">+</span> Treatment <span class="sc">+</span> distance<span class="sc">:</span>Treatment, </span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> Animal_ID, </span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> sholl_data)</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(sholl_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   numDF denDF  F-value p-value
(Intercept)            1   527 733.4385  &lt;.0001
distance              24   527 468.5021  &lt;.0001
Treatment              1   527  22.1407  &lt;.0001
distance:Treatment    24   527   8.3140  &lt;.0001</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>sholl_modelem <span class="ot">&lt;-</span> emmeans<span class="sc">::</span><span class="fu">emmeans</span>(sholl_model, pairwise <span class="sc">~</span> Treatment <span class="sc">|</span> distance) <span class="co"># point estimates given Treatment given distance</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Expand to show print out of <strong>sholl_modelem</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sholl_modelem)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="do">## $emmeans</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 5:</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    5.8215 0.351 22    5.094    6.549</span></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        6.1725 0.378 22    5.389    6.956</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 10:</span></span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    8.0523 0.351 22    7.325    8.780</span></span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        8.2634 0.378 22    7.480    9.047</span></span>
<span id="cb78-12"><a href="#cb78-12" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-13"><a href="#cb78-13" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 15:</span></span>
<span id="cb78-14"><a href="#cb78-14" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-15"><a href="#cb78-15" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control   10.3600 0.351 22    9.632   11.088</span></span>
<span id="cb78-16"><a href="#cb78-16" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        9.8089 0.378 22    9.026   10.592</span></span>
<span id="cb78-17"><a href="#cb78-17" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-18"><a href="#cb78-18" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 20:</span></span>
<span id="cb78-19"><a href="#cb78-19" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-20"><a href="#cb78-20" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control   12.2061 0.351 22   11.479   12.934</span></span>
<span id="cb78-21"><a href="#cb78-21" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX       10.8998 0.378 22   10.117   11.683</span></span>
<span id="cb78-22"><a href="#cb78-22" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-23"><a href="#cb78-23" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 25:</span></span>
<span id="cb78-24"><a href="#cb78-24" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-25"><a href="#cb78-25" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control   13.1292 0.351 22   12.402   13.857</span></span>
<span id="cb78-26"><a href="#cb78-26" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX       11.1725 0.378 22   10.389   11.956</span></span>
<span id="cb78-27"><a href="#cb78-27" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-28"><a href="#cb78-28" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 30:</span></span>
<span id="cb78-29"><a href="#cb78-29" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-30"><a href="#cb78-30" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control   13.1292 0.351 22   12.402   13.857</span></span>
<span id="cb78-31"><a href="#cb78-31" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX       10.7180 0.378 22    9.935   11.501</span></span>
<span id="cb78-32"><a href="#cb78-32" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-33"><a href="#cb78-33" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 35:</span></span>
<span id="cb78-34"><a href="#cb78-34" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-35"><a href="#cb78-35" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control   12.7446 0.351 22   12.017   13.472</span></span>
<span id="cb78-36"><a href="#cb78-36" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        9.8998 0.378 22    9.117   10.683</span></span>
<span id="cb78-37"><a href="#cb78-37" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-38"><a href="#cb78-38" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 40:</span></span>
<span id="cb78-39"><a href="#cb78-39" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-40"><a href="#cb78-40" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control   11.5908 0.351 22   10.863   12.318</span></span>
<span id="cb78-41"><a href="#cb78-41" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        8.4452 0.378 22    7.662    9.228</span></span>
<span id="cb78-42"><a href="#cb78-42" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-43"><a href="#cb78-43" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 45:</span></span>
<span id="cb78-44"><a href="#cb78-44" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-45"><a href="#cb78-45" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control   10.5908 0.351 22    9.863   11.318</span></span>
<span id="cb78-46"><a href="#cb78-46" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        6.8998 0.378 22    6.117    7.683</span></span>
<span id="cb78-47"><a href="#cb78-47" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-48"><a href="#cb78-48" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 50:</span></span>
<span id="cb78-49"><a href="#cb78-49" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-50"><a href="#cb78-50" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    8.5138 0.351 22    7.786    9.241</span></span>
<span id="cb78-51"><a href="#cb78-51" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        5.6271 0.378 22    4.844    6.410</span></span>
<span id="cb78-52"><a href="#cb78-52" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-53"><a href="#cb78-53" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 55:</span></span>
<span id="cb78-54"><a href="#cb78-54" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-55"><a href="#cb78-55" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    6.7446 0.351 22    6.017    7.472</span></span>
<span id="cb78-56"><a href="#cb78-56" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        4.5362 0.378 22    3.753    5.319</span></span>
<span id="cb78-57"><a href="#cb78-57" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-58"><a href="#cb78-58" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 60:</span></span>
<span id="cb78-59"><a href="#cb78-59" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-60"><a href="#cb78-60" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    5.2831 0.351 22    4.555    6.011</span></span>
<span id="cb78-61"><a href="#cb78-61" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        3.4452 0.378 22    2.662    4.228</span></span>
<span id="cb78-62"><a href="#cb78-62" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-63"><a href="#cb78-63" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 65:</span></span>
<span id="cb78-64"><a href="#cb78-64" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-65"><a href="#cb78-65" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    3.9754 0.351 22    3.248    4.703</span></span>
<span id="cb78-66"><a href="#cb78-66" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        2.1725 0.378 22    1.389    2.956</span></span>
<span id="cb78-67"><a href="#cb78-67" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-68"><a href="#cb78-68" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 70:</span></span>
<span id="cb78-69"><a href="#cb78-69" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-70"><a href="#cb78-70" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    2.5908 0.351 22    1.863    3.318</span></span>
<span id="cb78-71"><a href="#cb78-71" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        1.3543 0.378 22    0.571    2.138</span></span>
<span id="cb78-72"><a href="#cb78-72" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-73"><a href="#cb78-73" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 75:</span></span>
<span id="cb78-74"><a href="#cb78-74" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-75"><a href="#cb78-75" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    1.7446 0.351 22    1.017    2.472</span></span>
<span id="cb78-76"><a href="#cb78-76" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        0.9907 0.378 22    0.207    1.774</span></span>
<span id="cb78-77"><a href="#cb78-77" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-78"><a href="#cb78-78" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 80:</span></span>
<span id="cb78-79"><a href="#cb78-79" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-80"><a href="#cb78-80" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    1.2831 0.351 22    0.555    2.011</span></span>
<span id="cb78-81"><a href="#cb78-81" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        0.6271 0.378 22   -0.156    1.410</span></span>
<span id="cb78-82"><a href="#cb78-82" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-83"><a href="#cb78-83" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 85:</span></span>
<span id="cb78-84"><a href="#cb78-84" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-85"><a href="#cb78-85" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    0.7446 0.351 22    0.017    1.472</span></span>
<span id="cb78-86"><a href="#cb78-86" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        0.3543 0.378 22   -0.429    1.138</span></span>
<span id="cb78-87"><a href="#cb78-87" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-88"><a href="#cb78-88" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 90:</span></span>
<span id="cb78-89"><a href="#cb78-89" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-90"><a href="#cb78-90" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    0.5138 0.351 22   -0.214    1.241</span></span>
<span id="cb78-91"><a href="#cb78-91" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        0.1725 0.378 22   -0.611    0.956</span></span>
<span id="cb78-92"><a href="#cb78-92" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-93"><a href="#cb78-93" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 95:</span></span>
<span id="cb78-94"><a href="#cb78-94" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-95"><a href="#cb78-95" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    0.3600 0.351 22   -0.368    1.088</span></span>
<span id="cb78-96"><a href="#cb78-96" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        0.0816 0.378 22   -0.702    0.865</span></span>
<span id="cb78-97"><a href="#cb78-97" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-98"><a href="#cb78-98" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 100:</span></span>
<span id="cb78-99"><a href="#cb78-99" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-100"><a href="#cb78-100" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control    0.0523 0.351 22   -0.675    0.780</span></span>
<span id="cb78-101"><a href="#cb78-101" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        0.0816 0.378 22   -0.702    0.865</span></span>
<span id="cb78-102"><a href="#cb78-102" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-103"><a href="#cb78-103" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 105:</span></span>
<span id="cb78-104"><a href="#cb78-104" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-105"><a href="#cb78-105" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control   -0.0246 0.351 22   -0.752    0.703</span></span>
<span id="cb78-106"><a href="#cb78-106" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        0.0816 0.378 22   -0.702    0.865</span></span>
<span id="cb78-107"><a href="#cb78-107" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-108"><a href="#cb78-108" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 110:</span></span>
<span id="cb78-109"><a href="#cb78-109" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-110"><a href="#cb78-110" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control   -0.1015 0.351 22   -0.829    0.626</span></span>
<span id="cb78-111"><a href="#cb78-111" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        0.0816 0.378 22   -0.702    0.865</span></span>
<span id="cb78-112"><a href="#cb78-112" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-113"><a href="#cb78-113" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 115:</span></span>
<span id="cb78-114"><a href="#cb78-114" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-115"><a href="#cb78-115" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control   -0.1015 0.351 22   -0.829    0.626</span></span>
<span id="cb78-116"><a href="#cb78-116" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        0.0973 0.391 22   -0.714    0.908</span></span>
<span id="cb78-117"><a href="#cb78-117" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-118"><a href="#cb78-118" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 120:</span></span>
<span id="cb78-119"><a href="#cb78-119" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-120"><a href="#cb78-120" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control   -0.1015 0.351 22   -0.829    0.626</span></span>
<span id="cb78-121"><a href="#cb78-121" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        0.0816 0.378 22   -0.702    0.865</span></span>
<span id="cb78-122"><a href="#cb78-122" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-123"><a href="#cb78-123" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 125:</span></span>
<span id="cb78-124"><a href="#cb78-124" aria-hidden="true" tabindex="-1"></a><span class="do">##  Treatment  emmean    SE df lower.CL upper.CL</span></span>
<span id="cb78-125"><a href="#cb78-125" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control   -0.1015 0.351 22   -0.829    0.626</span></span>
<span id="cb78-126"><a href="#cb78-126" aria-hidden="true" tabindex="-1"></a><span class="do">##  PLX        0.0816 0.378 22   -0.702    0.865</span></span>
<span id="cb78-127"><a href="#cb78-127" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-128"><a href="#cb78-128" aria-hidden="true" tabindex="-1"></a><span class="do">## Degrees-of-freedom method: containment </span></span>
<span id="cb78-129"><a href="#cb78-129" aria-hidden="true" tabindex="-1"></a><span class="do">## Confidence level used: 0.95 </span></span>
<span id="cb78-130"><a href="#cb78-130" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-131"><a href="#cb78-131" aria-hidden="true" tabindex="-1"></a><span class="do">## $contrasts</span></span>
<span id="cb78-132"><a href="#cb78-132" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 5:</span></span>
<span id="cb78-133"><a href="#cb78-133" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-134"><a href="#cb78-134" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX  -0.3510 0.482 527  -0.729  0.4665</span></span>
<span id="cb78-135"><a href="#cb78-135" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-136"><a href="#cb78-136" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 10:</span></span>
<span id="cb78-137"><a href="#cb78-137" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-138"><a href="#cb78-138" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX  -0.2111 0.482 527  -0.438  0.6613</span></span>
<span id="cb78-139"><a href="#cb78-139" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-140"><a href="#cb78-140" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 15:</span></span>
<span id="cb78-141"><a href="#cb78-141" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-142"><a href="#cb78-142" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   0.5511 0.482 527   1.144  0.2531</span></span>
<span id="cb78-143"><a href="#cb78-143" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-144"><a href="#cb78-144" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 20:</span></span>
<span id="cb78-145"><a href="#cb78-145" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-146"><a href="#cb78-146" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   1.3064 0.482 527   2.712  0.0069</span></span>
<span id="cb78-147"><a href="#cb78-147" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-148"><a href="#cb78-148" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 25:</span></span>
<span id="cb78-149"><a href="#cb78-149" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-150"><a href="#cb78-150" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   1.9567 0.482 527   4.062  0.0001</span></span>
<span id="cb78-151"><a href="#cb78-151" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-152"><a href="#cb78-152" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 30:</span></span>
<span id="cb78-153"><a href="#cb78-153" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-154"><a href="#cb78-154" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   2.4113 0.482 527   5.006  &lt;.0001</span></span>
<span id="cb78-155"><a href="#cb78-155" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-156"><a href="#cb78-156" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 35:</span></span>
<span id="cb78-157"><a href="#cb78-157" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-158"><a href="#cb78-158" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   2.8448 0.482 527   5.906  &lt;.0001</span></span>
<span id="cb78-159"><a href="#cb78-159" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-160"><a href="#cb78-160" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 40:</span></span>
<span id="cb78-161"><a href="#cb78-161" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-162"><a href="#cb78-162" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   3.1455 0.482 527   6.530  &lt;.0001</span></span>
<span id="cb78-163"><a href="#cb78-163" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-164"><a href="#cb78-164" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 45:</span></span>
<span id="cb78-165"><a href="#cb78-165" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-166"><a href="#cb78-166" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   3.6910 0.482 527   7.663  &lt;.0001</span></span>
<span id="cb78-167"><a href="#cb78-167" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-168"><a href="#cb78-168" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 50:</span></span>
<span id="cb78-169"><a href="#cb78-169" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-170"><a href="#cb78-170" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   2.8868 0.482 527   5.993  &lt;.0001</span></span>
<span id="cb78-171"><a href="#cb78-171" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-172"><a href="#cb78-172" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 55:</span></span>
<span id="cb78-173"><a href="#cb78-173" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-174"><a href="#cb78-174" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   2.2085 0.482 527   4.585  &lt;.0001</span></span>
<span id="cb78-175"><a href="#cb78-175" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-176"><a href="#cb78-176" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 60:</span></span>
<span id="cb78-177"><a href="#cb78-177" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-178"><a href="#cb78-178" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   1.8378 0.482 527   3.816  0.0002</span></span>
<span id="cb78-179"><a href="#cb78-179" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-180"><a href="#cb78-180" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 65:</span></span>
<span id="cb78-181"><a href="#cb78-181" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-182"><a href="#cb78-182" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   1.8029 0.482 527   3.743  0.0002</span></span>
<span id="cb78-183"><a href="#cb78-183" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-184"><a href="#cb78-184" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 70:</span></span>
<span id="cb78-185"><a href="#cb78-185" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-186"><a href="#cb78-186" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   1.2364 0.482 527   2.567  0.0105</span></span>
<span id="cb78-187"><a href="#cb78-187" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-188"><a href="#cb78-188" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 75:</span></span>
<span id="cb78-189"><a href="#cb78-189" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-190"><a href="#cb78-190" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   0.7539 0.482 527   1.565  0.1181</span></span>
<span id="cb78-191"><a href="#cb78-191" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-192"><a href="#cb78-192" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 80:</span></span>
<span id="cb78-193"><a href="#cb78-193" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-194"><a href="#cb78-194" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   0.6560 0.482 527   1.362  0.1738</span></span>
<span id="cb78-195"><a href="#cb78-195" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-196"><a href="#cb78-196" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 85:</span></span>
<span id="cb78-197"><a href="#cb78-197" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-198"><a href="#cb78-198" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   0.3903 0.482 527   0.810  0.4182</span></span>
<span id="cb78-199"><a href="#cb78-199" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-200"><a href="#cb78-200" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 90:</span></span>
<span id="cb78-201"><a href="#cb78-201" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-202"><a href="#cb78-202" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   0.3413 0.482 527   0.709  0.4789</span></span>
<span id="cb78-203"><a href="#cb78-203" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-204"><a href="#cb78-204" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 95:</span></span>
<span id="cb78-205"><a href="#cb78-205" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-206"><a href="#cb78-206" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX   0.2784 0.482 527   0.578  0.5635</span></span>
<span id="cb78-207"><a href="#cb78-207" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-208"><a href="#cb78-208" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 100:</span></span>
<span id="cb78-209"><a href="#cb78-209" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-210"><a href="#cb78-210" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX  -0.0293 0.482 527  -0.061  0.9515</span></span>
<span id="cb78-211"><a href="#cb78-211" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-212"><a href="#cb78-212" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 105:</span></span>
<span id="cb78-213"><a href="#cb78-213" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-214"><a href="#cb78-214" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX  -0.1062 0.482 527  -0.221  0.8255</span></span>
<span id="cb78-215"><a href="#cb78-215" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-216"><a href="#cb78-216" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 110:</span></span>
<span id="cb78-217"><a href="#cb78-217" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-218"><a href="#cb78-218" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX  -0.1831 0.482 527  -0.380  0.7039</span></span>
<span id="cb78-219"><a href="#cb78-219" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-220"><a href="#cb78-220" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 115:</span></span>
<span id="cb78-221"><a href="#cb78-221" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-222"><a href="#cb78-222" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX  -0.1989 0.492 527  -0.404  0.6862</span></span>
<span id="cb78-223"><a href="#cb78-223" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-224"><a href="#cb78-224" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 120:</span></span>
<span id="cb78-225"><a href="#cb78-225" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-226"><a href="#cb78-226" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX  -0.1831 0.482 527  -0.380  0.7039</span></span>
<span id="cb78-227"><a href="#cb78-227" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-228"><a href="#cb78-228" aria-hidden="true" tabindex="-1"></a><span class="do">## distance = 125:</span></span>
<span id="cb78-229"><a href="#cb78-229" aria-hidden="true" tabindex="-1"></a><span class="do">##  contrast      estimate    SE  df t.ratio p.value</span></span>
<span id="cb78-230"><a href="#cb78-230" aria-hidden="true" tabindex="-1"></a><span class="do">##  Control - PLX  -0.1831 0.482 527  -0.380  0.7039</span></span>
<span id="cb78-231"><a href="#cb78-231" aria-hidden="true" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb78-232"><a href="#cb78-232" aria-hidden="true" tabindex="-1"></a><span class="do">## Degrees-of-freedom method: containment</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get data frame of point estimates and CIs</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>sholl_emm <span class="ot">&lt;-</span> <span class="fu">summary</span>(sholl_modelem<span class="sc">$</span>emmeans)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>sholl_posthoc_tvals <span class="ot">&lt;-</span> sholl_data <span class="sc">%&gt;%</span> </span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(distance) <span class="sc">%&gt;%</span> </span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">emmeans_test</span>(intern_C <span class="sc">~</span> Treatment, <span class="at">model =</span> sholl_model) <span class="sc">%&gt;%</span> </span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p.adj =</span> <span class="fu">p.adjust</span>(p,  <span class="at">method =</span> <span class="st">'bonferroni'</span>),</span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">p.adj.signif =</span> <span class="fu">case_when</span>(p.adj <span class="sc">&lt;</span> <span class="fl">0.001</span> <span class="sc">~</span> <span class="st">"***"</span>,</span>
<span id="cb79-9"><a href="#cb79-9" aria-hidden="true" tabindex="-1"></a>                                  p.adj <span class="sc">&lt;</span> <span class="fl">0.01</span> <span class="sc">~</span> <span class="st">"**"</span>,</span>
<span id="cb79-10"><a href="#cb79-10" aria-hidden="true" tabindex="-1"></a>                                  p.adj <span class="sc">&lt;</span> <span class="fl">0.05</span> <span class="sc">~</span> <span class="st">"*"</span>,</span>
<span id="cb79-11"><a href="#cb79-11" aria-hidden="true" tabindex="-1"></a>                                  p.adj <span class="sc">&gt;=</span> <span class="fl">0.05</span> <span class="sc">~</span> <span class="st">''</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb79-12"><a href="#cb79-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(group1, group2, distance, df, statistic, p, p.adj, p.adj.signif)</span>
<span id="cb79-13"><a href="#cb79-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-14"><a href="#cb79-14" aria-hidden="true" tabindex="-1"></a>sholl_subject <span class="ot">&lt;-</span> sholl_data <span class="sc">%&gt;%</span> </span>
<span id="cb79-15"><a href="#cb79-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Animal_ID, distance, Treatment) <span class="sc">%&gt;%</span> </span>
<span id="cb79-16"><a href="#cb79-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_inter =</span> <span class="fu">mean</span>(intern_C))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'Animal_ID', 'distance'. You can override
using the `.groups` argument.</code></pre>
</div>
</div>
</section>
</section>
<section id="step-5-visualize-branch-intersections-distance-treatment" class="level4">
<h4 class="anchored" data-anchor-id="step-5-visualize-branch-intersections-distance-treatment">Step 5: Visualize Branch intersections ~ <strong>distance</strong> + <strong>Treatment</strong></h4>
<p>Scatter dot plot with estimated means and 95% CI</p>
<p>This was very tricky but I kind of did it!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># p values</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>p_vals <span class="ot">&lt;-</span> sholl_posthoc_tvals <span class="sc">%&gt;%</span> </span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(group1, group2, distance, p.adj.signif) <span class="sc">%&gt;%</span> </span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p.adj.signif <span class="sc">!=</span> <span class="st">""</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">y.position =</span> <span class="dv">20</span><span class="sc">:</span><span class="dv">12</span>)</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a><span class="co"># define custom graph colors</span></span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>gray_scale <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"#A0A0A4"</span>, <span class="st">"#101010"</span>)</span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>base <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(sholl_data, </span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">x =</span> distance, <span class="at">y =</span> intern_C, <span class="at">group =</span> Treatment)) <span class="sc">+</span> </span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">factor</span>(Treatment)),</span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>),</span>
<span id="cb81-14"><a href="#cb81-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="fl">0.7</span>,</span>
<span id="cb81-15"><a href="#cb81-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb81-16"><a href="#cb81-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> sholl_emm, <span class="co"># Add emm</span></span>
<span id="cb81-17"><a href="#cb81-17" aria-hidden="true" tabindex="-1"></a>            <span class="fu">aes</span>(<span class="at">y =</span> emmean,</span>
<span id="cb81-18"><a href="#cb81-18" aria-hidden="true" tabindex="-1"></a>                <span class="at">color =</span> <span class="fu">factor</span>(Treatment)),</span>
<span id="cb81-19"><a href="#cb81-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb81-20"><a href="#cb81-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> sholl_emm, <span class="co"># Add emm CIs</span></span>
<span id="cb81-21"><a href="#cb81-21" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">y =</span> emmean, <span class="at">ymin =</span> lower.CL, <span class="at">ymax =</span> upper.CL,</span>
<span id="cb81-22"><a href="#cb81-22" aria-hidden="true" tabindex="-1"></a>                  <span class="at">fill =</span> <span class="fu">factor</span>(Treatment)),</span>
<span id="cb81-23"><a href="#cb81-23" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb81-24"><a href="#cb81-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="fu">levels</span>(sholl_data<span class="sc">$</span>distance)), </span>
<span id="cb81-25"><a href="#cb81-25" aria-hidden="true" tabindex="-1"></a>                   <span class="at">breaks =</span> <span class="fu">c</span>(<span class="st">"0"</span>, <span class="fu">as.character</span>(<span class="fu">seq</span>(<span class="dv">25</span>, <span class="dv">125</span>, <span class="at">by =</span> <span class="dv">25</span>)))) <span class="sc">+</span></span>
<span id="cb81-26"><a href="#cb81-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span>.<span class="dv">9</span>, <span class="dv">20</span>)) <span class="sc">+</span></span>
<span id="cb81-27"><a href="#cb81-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Mean intersections (n)"</span>) <span class="sc">+</span></span>
<span id="cb81-28"><a href="#cb81-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"Distance from cell body ("</span>,mu,<span class="st">"m)"</span>))) <span class="sc">+</span></span>
<span id="cb81-29"><a href="#cb81-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Sholl Analysis"</span>) <span class="sc">+</span></span>
<span id="cb81-30"><a href="#cb81-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> p_vals<span class="sc">$</span>distance, </span>
<span id="cb81-31"><a href="#cb81-31" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> p_vals<span class="sc">$</span>y.position, </span>
<span id="cb81-32"><a href="#cb81-32" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> p_vals<span class="sc">$</span>p.adj.signif) <span class="sc">+</span></span>
<span id="cb81-33"><a href="#cb81-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">16</span>, <span class="at">y =</span> <span class="fl">19.5</span>, <span class="at">label =</span> <span class="st">"####"</span>)</span>
<span id="cb81-34"><a href="#cb81-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-35"><a href="#cb81-35" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> base <span class="sc">+</span> </span>
<span id="cb81-36"><a href="#cb81-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> gray_scale) <span class="sc">+</span></span>
<span id="cb81-37"><a href="#cb81-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> gray_scale) <span class="sc">+</span></span>
<span id="cb81-38"><a href="#cb81-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_prism</span>(<span class="at">base_size =</span> <span class="dv">12</span>,</span>
<span id="cb81-39"><a href="#cb81-39" aria-hidden="true" tabindex="-1"></a>              <span class="at">base_fontface =</span> <span class="st">"plain"</span>,</span>
<span id="cb81-40"><a href="#cb81-40" aria-hidden="true" tabindex="-1"></a>              <span class="at">base_family =</span> <span class="st">"Arial"</span>) <span class="sc">+</span> </span>
<span id="cb81-41"><a href="#cb81-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="fl">0.8</span>,<span class="fl">0.95</span>),</span>
<span id="cb81-42"><a href="#cb81-42" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.line =</span> <span class="fu">element_line</span>(<span class="at">linewidth =</span> <span class="fl">0.2</span>),</span>
<span id="cb81-43"><a href="#cb81-43" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_line</span>(<span class="at">linewidth =</span> <span class="fl">0.2</span>),</span>
<span id="cb81-44"><a href="#cb81-44" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb81-45"><a href="#cb81-45" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb81-46"><a href="#cb81-46" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks.length =</span> <span class="fu">unit</span>(<span class="fl">0.1</span>, <span class="st">"cm"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Save plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"ERC_fig4k.png"</span>, </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">width =</span> <span class="fl">3.5</span>, <span class="at">height =</span> <span class="dv">4</span>, <span class="at">units =</span> <span class="st">"in"</span>,</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">path =</span> <span class="st">"images/"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="comparison-of-results" class="level3">
<h3 class="anchored" data-anchor-id="comparison-of-results">Comparison of Results</h3>
<div>

</div>
<div class="quarto-layout-panel" data-layout="[52,48]">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell" style="flex-basis: 52.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig4k.png" class="img-fluid figure-img"></p>
<figcaption>Paper: Hierarchical linear mixed-effects model</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 48.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ERC_fig4k.png" class="img-fluid figure-img"></p>
<figcaption>Mine: Linear mixed-effects model <sup>####</sup>p&lt;0.0001 main effect, **p&lt;0.01, ***p&lt;0.001 from bonferroni post-hoc</figcaption>
</figure>
</div>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Sholl analysis detected that microglia from the treatment group had fewer and less expansive branches than controls. Microglia from the treatment group had fewer branches intersecting the Sholl analysis circles (concentric circles every 5 μm from the cell body) than controls. Treatment n = 324 microglia (12 mice, 27 microglia/mouse), Control n = 345 microglia (13 mice, 27 microglia/mouse) (Fig. 4k).</p>
</blockquote>
</section>
</section>
<section id="discussion-and-reflection" class="level2">
<h2 class="anchored" data-anchor-id="discussion-and-reflection">Discussion and Reflection</h2>
<p>I successfully replicated the inferential statistical analyses and visualizations conducted on full photomicrographs of Iba1 percent coverage, both averaged by subject (Analysis 1) and including multiple photomicrographs per subject (Analysis 2). This consisted of running generalized linear mixed models with beta error distributions and calculating estimated means (and difference between means) and confidence intervals of the point estimates, and effect sizes. My values for differences between estimated means and effect sizes were negative, as the control value was smaller than the treatment (plx) value, but I took the absolute value for comparison (as I believe the authors did). It seems the authors converted the differences between estimated means to units of percent, while I left mine in units of proportion, as graphed.</p>
<p>Authors stated the photomicrograph-averaged mean percent coverage (Analysis 1) had a 70% smaller effect size than the photomicrograph-specific percent coverage (Analysis 2), which I verified (100 - ((0.0006 / 0.002) * 100) = 70%). However, unlike the authors I noted that the actual value of the effect size is still very small (0.002), which means the difference is negligible even if it is statistically significant.</p>
<p>Overall the DRYAD raw dataset was well described and organized for loading into R, and the statistical analyses were well described in the methods. However, I was not able to attempt replication of fractal analysis, as that data set was not available. I did have to transform the Animal_ID variable from type time to character, and it was not clear what each part (XX:XX:XX) of the Animal_ID meant. I also assumed the beta error distribution was transformed to log odds ratio scale. I was not familiar with this type of error distribution (nor {glmmTMB}), so it took some time to figure that out, and to use {emmeans} to get the inferential statistics. It would have been helpful if the authors had included the equation for each model in either the DRYAD dataset or methods section of the paper. They also did not incldue any R code, which obvisouly would have been immensely helpful for exact replication of analyses.</p>
<p>The visualizations were more straightforward than the inferential statistical analyses, but it took a lot of customization to match the aesthetics of the paper. I think I got pretty close!</p>
<p>As the original paper did not report any descriptive statistics, I was not able to compare my descriptive statistics to theirs, but doing an exploratory data analysis prior to generalized linear mixed modeling certainly helped to work out some of the kinks and get familiar with the data sets.</p>
<p>For an additional challenge, I also attempted to replicate their Sholl analysis. This was not as straightforward, and I was not successful, likely due to the introduction of nonlinear effects. I was able to partially replicate their visualization, showing point estimates and CIs rather than a model-derived curve and CI.</p>
<p>This assignment was very challenging, but I did learn a lot about data wrangling, generalized linear modeling, and visualization (as well as Quarto aesthetics).</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>